# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ast_ast}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Hawxwell"]
  s.date = %q{2010-09-28}
  s.description = %q{Easily convert strings to Tokens and then on to an Abstract Syntax Tree easily. (Very far from finished!)}
  s.email = %q{m@hawx.me}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "lib/ast_ast.rb",
     "lib/ast_ast/ast.rb",
     "lib/ast_ast/token.rb",
     "lib/ast_ast/tokeniser.rb",
     "lib/ast_ast/tokens.rb",
     "lib/ast_ast/tree.rb",
     "lib/ast_tokens.rb",
     "test/helper.rb",
     "test/test_ast_ast.rb",
     "test/test_tokeniser.rb"
  ]
  s.homepage = %q{http://github.com/hawx/ast_ast}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{String -> Tokens -> AST}
  s.test_files = [
    "test/helper.rb",
     "test/test_ast_ast.rb",
     "test/test_tokeniser.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

